#!/bin/bash -e

print_help () {
	echo "Usage: kisscsvplot -f [filename]"
	echo "Options:"
	echo "	-h:		print this help"
	echo "	-x:		Set x axis label"
	echo "	-y:		Set y axis label"
	echo "	-r:		plot a bode plot of re(Z)"
	echo "	-i:		plot a bode plot of im(Z)"
	echo "	-l:		allways use linear scale"
}

if ! command -v gnuplot &> /dev/null; then
	echo "gnuplot is required in \$PATH"
	exit
fi

mode="2:3"
xLabel='Z_{im}'
yLabel='Z_{re}'
logscale=""

while getopts "?rihy:x:f:l" opt; do
	case "$opt" in
	h|\?)
		print_help
		exit 0
		;;
	f)
		file=$OPTARG
		;;
	r)
		mode="1:2"
		xLabel='Omega'
		yLabel='Z_{re}'
		logscale="set logscale x;"
		;;
	i)
		mode="1:3"
		xLabel='Omega'
		yLabel='Z_{im}'
		logscale="set logscale x;"
	;;
	y)
		yLabel=$OPTARG
	;;
	x)
		xLabel=$OPTARG
	;;
	l)
		logscale=""
	;;
	esac
done

if [[ ! -f $file && $file != "-" ]]; then
	echo "a -f option must be given and it must be a regular file or - for stdin"
	exit 1
fi

if [[ $file != "-" ]]; then
	spectra="$(< $file)"
else
	spectra="$(< /dev/stdin)"
fi

header=$(echo "$spectra" | awk -F, 'NR==1{print $1}')
if [[ $header != "EISF" ]]; then
	echo "$file is not a valid EIS spectra file!"
	exit 1
fi

echo "$spectra" | gnuplot -p -e "\
set terminal qt enhanced font \",15\" title \"EIS Plot\"; \
set style line 1 lw 3 lc \"blue\"; \
set ylabel '$yLabel'; \
set xlabel '$xLabel'; \
$logscale \
set tics font \"Helvetica,12\"; \
set xlabel font \"Helvetica,15\"; \
set ylabel font \"Helvetica,15\"; \
set datafile separator ','; \
plot '-' using $mode skip 3 notitle w l;
"
