#!/bin/bash -e

PORJECT_NAME=@PROJECT_NAME@
SYSTEM_PROC=AMD64
VERSION="@CMAKE_PROJECT_VERSION_MAJOR@.@CMAKE_PROJECT_VERSION_MINOR@.@CMAKE_PROJECT_VERSION_PATCH@"
BINARYDIR="@CMAKE_CURRENT_BINARY_DIR@"
SRCDIR="@CMAKE_CURRENT_SOURCE_DIR@"
RELDIRECTORY="$BINARYDIR/packaged/$VERSION/release"
ZIPNAME=$PORJECT_NAME-$SYSTEM_PROC-$VERSION

rm $BINARYDIR/packaged/$ZIPNAME.zip || true
cd $BINARYDIR
install -d $RELDIRECTORY
cp libeisgenerator.dll $RELDIRECTORY
cp libeisgenerator.dll.a $RELDIRECTORY
cp libeisgenerator_static.a $RELDIRECTORY
cp eisgenerator_export.exe $RELDIRECTORY
cp eisgenerator_test.exe $RELDIRECTORY
cp $SRCDIR/gpl-3.0.txt $SRCDIR/lgpl-3.0.txt $RELDIRECTORY
cp $SRCDIR/README.md $RELDIRECTORY
cd $RELDIRECTORY/..
zip -r $BINARYDIR/packaged/$ZIPNAME.zip release
